/*
 * generated by Xtext 2.28.0
 */
package com.epstimis.uddl.query.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class QueryUiModule extends AbstractQueryUiModule {

	public QueryUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
