/*
 * generated by Xtext 2.28.0
 */
package com.epstimis.uddl.query.ide;

import com.epstimis.uddl.query.QueryRuntimeModule;
import com.epstimis.uddl.query.QueryStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class QueryIdeSetup extends QueryStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new QueryRuntimeModule(), new QueryIdeModule()));
	}
	
}
