/*
 * generated by Xtext 2.28.0
 */
package com.epistimis.uddl.query;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class QueryRuntimeModule extends AbstractQueryRuntimeModule {
}
