/*
 * generated by Xtext 2.33.0
 */
/*
 * Copyright (c) 2022 - 2024 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.query;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class QueryRuntimeModule extends AbstractQueryRuntimeModule {
}
