name: Build and Install 

on:
  workflow_dispatch
  # push:
  #   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  # Runner environment (OS)
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: https://github.com/Epistimis/FACE-Template-Language.git
          
      - name: Build and install face-template-language
        run: mvn clean install

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: https://github.com/Epistimis/xtext-docs-gen.git
          
      - name: Build and install xtext-docs
        run: mvn clean install

      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: https://github.com/Epistimis/UDDL-Query-Language.git
          
      - name: Build and install UDDL-Query
        run: mvn clean install

      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: https://github.com/Epistimis/UDDL.git
          
      - name: Build and install UDDL
        run: mvn clean install

      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: https://github.com/Epistimis/FACE.git
          
      - name: Build and install FACE
        run: mvn clean install
